# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  AZURE_WEBAPP_PACKAGE_PATH: published

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create release date file
      run: echo "partial class Program{public static readonly DateTime ReleaseDate=DateTime.Parse(\"$(date -u --iso-8601=seconds)\");}" > ${{ github.event.repository.name }}/Program.CI.cs
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Publish
      run: dotnet publish "${{ github.event.repository.name }}" --configuration ${{ env.CONFIGURATION }} --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/wwwroot
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
